Review all files with Codex and Claude

diff --git a/apple b/apple
--- a/apple
+++ b/apple
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # DESCRIPTION
-#   Print system info to the console.
+#   Print system information to the console.
 #
 # USAGE
 #   apple [OPTIONS]
@@ -14,11 +14,11 @@
 #   -h, --help     Show this help message
 #
 # EXAMPLES
-#   None
+#  apple --color
 
 # Print usage information.
 function usage() {
-  echo "usage: $0 [OPTIONS]"
+  echo "usage: apple [OPTIONS]"
   echo ""
   echo "Options:"
   echo "  -c, --color    Whether to colorize output"
@@ -49,17 +49,44 @@ if [ "${color}" == "true" ]; then
   reset='\033[0m'
 fi
 
+if ! [ -x "$(command -v sw_vers)" ]; then
+  echo -e "${red}ERROR: sw_vers is not installed.${reset}" >&2
+  exit 1
+fi
+
+if ! [ -x "$(command -v curl)" ]; then
+  echo -e "${red}ERROR: curl is not installed.${reset}" >&2
+  exit 1
+fi
+
+if ! [ -x "$(command -v brew)" ]; then
+  echo -e "${red}ERROR: brew is not installed.${reset}" >&2
+  exit 1
+fi
+
 user=$(whoami)
 hostname=$(hostname | sed 's/.local//g')
 
-version="OS X $(sw_vers -productVersion)"
+version="macOS $(sw_vers -productVersion)"
 version_number=$(sw_vers -productVersion)
 version_major=$(echo "${version_number}" | cut -d'.' -f1)
 version_minor=$(echo "${version_number}" | cut -d'.' -f2)
 version_short="${version_major}.${version_minor}"
 
 case "${version_short}" in
-  11.6)
+  15.0|15.1|15.2)
+    version_string="Sequoia"
+    ;;
+  14.0|14.1|14.2|14.3|14.4|14.5|14.6|14.7)
+    version_string="Sonoma"
+    ;;
+  13.0|13.1|13.2|13.3|13.4|13.5|13.6|13.7)
+    version_string="Ventura"
+    ;;
+  12.0|12.1|12.2|12.3|12.4|12.5|12.6|12.7)
+    version_string="Monterey"
+    ;;
+  11.0|11.1|11.2|11.3|11.4|11.5|11.6|11.7)
     version_string="Big Sur"
     ;;
   10.15)
diff --git a/aws-credentials b/aws-credentials
--- a/aws-credentials
+++ b/aws-credentials
@@ -30,7 +30,7 @@ reset='\033[0m'
 
 # Print usage information.
 function usage() {
-  echo "usage: $0 [OPTIONS] PROFILE"
+  echo "usage: aws-credentials [OPTIONS] PROFILE"
   echo ""
   echo "Arguments:"
   echo "  PROFILE    Named profile for the AWS CLI"
@@ -54,6 +54,11 @@ done
 if [ -z "${profile}" ]; then
   echo -e "${red}ERROR: Must specify a profile.${reset}" >&2
   usage
+  exit 1
+fi
+
+if ! [ -x "$(command -v gsed)" ]; then
+  echo -e "${red}ERROR: gsed is not installed.${reset}" >&2
   exit 1
 fi
 
@@ -103,10 +108,10 @@ EOD
 )
 
 credentials=$(tail -n 4 <<< "${content}")
-gsed -i "/${1}/,+4d" "${HOME}/.aws/credentials"
+gsed -i "/${profile}/,+4d" "${HOME}/.aws/credentials"
 cat <<EOT >> "${HOME}/.aws/credentials"
 
-[${1}]
+[${profile}]
 ${credentials}
 EOT
 gsed -i 's/\\$//;/./,/^$/!d' "${HOME}/.aws/credentials"
diff --git a/git-clone-gh b/git-clone-gh
--- a/git-clone-gh
+++ b/git-clone-gh
@@ -39,7 +39,7 @@ reset='\033[0m'
 
 # Print usage information.
 function usage() {
-  echo "usage: $0 [OPTIONS] [TOKEN]"
+  echo "usage: git-clone-gh [OPTIONS] [TOKEN]"
   echo ""
   echo "Arguments:"
   echo "  TOKEN    GitHub personal access token"
@@ -63,9 +63,9 @@ access_token=""
 # Parse command line arguments.
 while [[ $# -gt 0 ]]; do
   case $1 in
-    -u|--user) user="$2"; shift 2 ;;
-    -o|--org) org="$2"; shift 2 ;;
-    -i|--identity-file) identity_file="$2"; shift 2 ;;
+    -u|--user) user=$2; shift 2 ;;
+    -o|--org) org=$2; shift 2 ;;
+    -i|--identity-file) identity_file=$2; shift 2 ;;
     -s|--skip-archived) skip_archived=true; shift ;;
     -h|--help) usage; exit 0 ;;
     -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
@@ -94,9 +94,8 @@ fi
 eval "$(ssh-agent -s)" >/dev/null 2>&1 && \
   ssh-add "${HOME}/.ssh/${identity_file}" >/dev/null 2>&1
 
-trap 'ssh git@github.com >/dev/null 2>&1 || EXIT=$?' ERR
-
-if [ "${EXIT}" == "255" ]; then
+# Test SSH connection to GitHub.
+if ! ssh -T git@github.com >/dev/null 2>&1; then
   echo -e "${red}ERROR: Permission denied (publickey).${reset}" >&2
   exit 1
 fi
@@ -130,33 +129,30 @@ fi
 page=1
 ssh_urls=()
 while true; do
-  urls=($(curl -L --silent -X GET \
-    --header "Authorization: Token ${access_token}" \
-    "https://api.github.com/${resource}?sort=full_name&page=${page}" | \
-    jq -r "${jq_filter}"))
+  mapfile -t urls <<EOF_URLS
+$(curl -L --silent -X GET \
+  --header "Authorization: Token ${access_token}" \
+  "https://api.github.com/${resource}?sort=full_name&page=${page}" | \
+  jq -r "${jq_filter}")
+EOF_URLS
   if [ ${#urls[@]} -eq 0 ]; then
     break
-  else
-    ssh_urls+=("${urls[@]}")
   fi
-  (( page=page+1 ))
+  ssh_urls+=("${urls[@]}")
+  ((page++))
 done
 
 for ssh_url in "${ssh_urls[@]}"; do
-
   echo Cloning "${ssh_url}"...
-
   output=$(git clone "${ssh_url}" 2>&1)
-
-  if [[ "${output}" =~ 'already exists' ]]; then
+  if echo "${output}" | grep -qi "already exists"; then
     echo -e "${red}Repository already exists.${reset}"
-  elif [[ "${output}" =~ 'not found' ]]; then
+  elif echo "${output}" | grep -qi "not found"; then
     echo -e "${red}Please make sure you have the correct access rights and the repository exists.${reset}"
-  elif [[ "${output}" =~ 'SAML' ]]; then
+  elif echo "${output}" | grep -qi "SAML"; then
     echo -e "${red}ERROR: The '${org}' organization has enabled or enforced SAML SSO${reset}" >&2
   fi
-
 done
 
-# Clean up ssh-agent
+# Clean up ssh-agent.
 ssh-agent -k >/dev/null 2>&1
diff --git a/git-clone-gl b/git-clone-gl
--- a/git-clone-gl
+++ b/git-clone-gl
@@ -37,7 +37,7 @@ reset='\033[0m'
 
 # Print usage information.
 function usage() {
-  echo "usage: $0 [OPTIONS] GROUP [TOKEN]"
+  echo "usage: git-clone-gl [OPTIONS] GROUP [TOKEN]"
   echo ""
   echo "Arguments:"
   echo "  GROUP    GitLab group"
@@ -74,7 +74,7 @@ if [ -z "${group}" ]; then
   exit 1
 fi
 
-# If no access token provided as argument, check environment variable
+# If no access token provided as argument, check environment variable.
 if [ -z "${access_token}" ]; then
   access_token="${GITLAB_API_TOKEN}"
 fi
@@ -85,17 +85,16 @@ if [ -z "${access_token}" ]; then
   exit 1
 fi
 
-eval $(ssh-agent -s) >/dev/null 2>&1 && \
-  ssh-add ~/.ssh/id_rsa >/dev/null 2>&1
+eval "$(ssh-agent -s)" >/dev/null 2>&1 && \
+  ssh-add "${HOME}/.ssh/id_rsa" >/dev/null 2>&1
 
-ssh git@gitlab.internal.granular.ag >/dev/null 2>&1
-
-if [ $? -eq 255 ]; then
+# Test SSH connection to GitLab.
+if ! ssh -T git@gitlab.internal.granular.ag >/dev/null 2>&1; then
   echo -e "${red}ERROR: Permission denied (publickey).${reset}" >&2
   exit 1
 fi
 
-# Encode URL (convert '\' to '%2f')
+# Encode URL (convert '\' to '%2f').
 group=$(echo "${group}" | sed "s/\//%2f/")
 
 # The GitLab API returns a maximum of 100 results per page. Therefore, we
@@ -103,31 +102,26 @@ group=$(echo "${group}" | sed "s/\//%2f/")
 page=1
 ssh_urls=()
 while true; do
-  urls=($(curl -L --silent -X GET \
-    --header "Authorization: Bearer ${access_token}" \
-    "https://gitlab.internal.granular.ag/api/v4/groups/${group}/projects?per_page=100&page=${page}&order_by=name&with_shared=false" \
-    | jq '.[].ssh_url_to_repo' \
-    | tr -d \"))
-
+  mapfile -t urls <<EOF_URLS
+$(curl -L --silent -X GET \
+  --header "Authorization: Bearer ${access_token}" \
+  "https://gitlab.internal.granular.ag/api/v4/groups/${group}/projects?per_page=100&page=${page}&order_by=name&with_shared=false" \
+  | jq -r '.[].ssh_url_to_repo')
+EOF_URLS
   if [ ${#urls[@]} -eq 0 ]; then
     break
-  else
-    ssh_urls+=("${urls[@]}")
   fi
-  (( page=page+1 ))
+  ssh_urls+=("${urls[@]}")
+  ((page++))
 done
 
 for ssh_url in "${ssh_urls[@]}"; do
-
   echo Cloning "${ssh_url}"...
-
   output=$(git clone "${ssh_url}" 2>&1)
-
-  if [ $(echo "${output}" | grep -i "already exists" -c) -ne 0 ]; then
+  if echo "${output}" | grep -qi "already exists"; then
     echo -e "${red}Repository already exists.${reset}"
   fi
-
 done
 
-# Clean up ssh-agent
+# Clean up ssh-agent.
 ssh-agent -k >/dev/null 2>&1
diff --git a/git-config-all b/git-config-all
--- a/git-config-all
+++ b/git-config-all
@@ -35,7 +35,7 @@ reset='\033[0m'
 
 # Print usage information.
 function usage() {
-  echo "usage: $0 [OPTIONS] USERNAME EMAIL HOST"
+  echo "usage: git-config-all [OPTIONS] USERNAME EMAIL HOST"
   echo ""
   echo "Arguments:"
   echo "  USERNAME    Username to set"
@@ -88,13 +88,18 @@ if [ -z "${host}" ]; then
   exit 1
 fi
 
-for d in *; do \
+if ! [ -x "$(command -v gsed)" ]; then
+  echo -e "${red}ERROR: gsed is not installed.${reset}" >&2
+  exit 1
+fi
+
+for d in *; do
   if [ -d "${d}" ]; then
     pushd "${d}" >/dev/null || exit
     git config user.name "${user_name}" && \
     git config user.email "${user_email}"
-    orl_url="$(git remote get-url origin)"
-    new_url=$(echo "${orl_url}" | gsed -E "s/@(.*):/@${host}:/")
+    old_url="$(git remote get-url origin)"
+    new_url=$(echo "${old_url}" | gsed -E "s/@(.*):/@${host}:/")
     git remote set-url origin "${new_url}"
     popd >/dev/null || exit
   fi
