Standardize color and error output

diff --git a/aws-credentials b/aws-credentials
--- a/aws-credentials
+++ b/aws-credentials
@@ -24,6 +24,10 @@
 # EXAMPLES
 #   aws-credentials workiva.prod
 
+# Colors
+red='\033[0;31m'
+reset='\033[0m'
+
 # Print usage information.
 function usage() {
   echo "usage: $0 [OPTIONS] PROFILE"
@@ -48,9 +52,7 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [ -z "${profile}" ]; then
-  echo -en "\033[0;31m"
-  echo "ERROR: Must specify a profile." >&2
-  echo -en "\033[0m"
+  echo -e "${red}ERROR: Must specify a profile.${reset}" >&2
   usage
   exit 1
 fi
@@ -69,13 +71,11 @@ case "${profile}" in
     url="https://wkt-saml-cli.wkt.workiva.net"
     ;;
   *)
-    echo -en "\033[0;31m"
-    echo "ERROR: 'profile' must be one of:" >&2
+    echo -e "${red}ERROR: 'profile' must be one of:" >&2
     echo "  * workiva.corp"
     echo "  * workiva.prod"
     echo "  * workiva.dev"
-    echo "  * workiva.internal"
-    echo -en "\033[0m"
+    echo "  * workiva.internal${reset}" >&2
     exit 1
     ;;
 esac
diff --git a/generate-kubeconfig b/generate-kubeconfig
--- a/generate-kubeconfig
+++ b/generate-kubeconfig
@@ -20,6 +20,10 @@
 # EXAMPLES
 #   generate-kubeconfig --output ~/.kube/workiva.yaml --use-pem-file --use-aws-cli
 
+# Colors
+red='\033[0;31m'
+reset='\033[0m'
+
 # Print usage information.
 function usage() {
   echo "usage: $0 [OPTIONS]"
@@ -50,17 +54,13 @@ done
 
 # Check if 'output_file' is set. If not, exit with non-zero error code.
 if [ -z "${output_file}" ]; then
-  echo -en "\033[0;31m"
-  echo "ERROR: Specify an output file (ex. ~/.kube/workiva.yaml)." >&2
-  echo -en "\033[0m\n"
+  echo -e "${red}ERROR: Specify an output file (ex. ~/.kube/workiva.yaml).${reset}" >&2
   usage
   exit 1
 fi
 
 if ! [ -x "$(command -v aws)"  ]; then
-  echo -en "\033[0;31m"
-  echo 'ERROR: AWS CLI is not installed.' >&2
-  echo -en "\033[0m\n"
+  echo -e "${red}ERROR: AWS CLI is not installed.${reset}" >&2
   usage
   exit 1
 fi
diff --git a/git-clone-gh b/git-clone-gh
--- a/git-clone-gh
+++ b/git-clone-gh
@@ -33,6 +33,10 @@
 #   git-clone-gh -u nickolashkraus ghp_xxx
 #   git-clone-gh -o Workiva ghp_xxx --skip-archived
 
+# Colors
+red='\033[0;31m'
+reset='\033[0m'
+
 # Print usage information.
 function usage() {
   echo "usage: $0 [OPTIONS] [TOKEN]"
@@ -71,9 +75,7 @@ done
 
 # Error if 'user' and 'org' are either both set or not set.
 if { [ -n "${user}" ] && [ -n "${org}" ]; } || { [ -z "${user}" ] && [ -z "${org}" ]; }; then
-  echo -en "\033[0;31m"
-  echo "ERROR: Specify either a user or organization." >&2
-  echo -en "\033[0m\n"
+  echo -e "${red}ERROR: Specify either a user or organization.${reset}" >&2
   usage
   exit 1
 fi
@@ -84,9 +86,7 @@ if [ -z "${access_token}" ]; then
 fi
 
 if [ -z "${access_token}" ]; then
-  echo -en "\033[0;31m"
-  echo "ERROR: Specify a GitHub access token." >&2
-  echo -en "\033[0m\n"
+  echo -e "${red}ERROR: Specify a GitHub access token.${reset}" >&2
   usage
   exit 1
 fi
@@ -97,9 +97,7 @@ eval "$(ssh-agent -s)" >/dev/null 2>&1 && \
 trap 'ssh git@github.com >/dev/null 2>&1 || EXIT=$?' ERR
 
 if [ "${EXIT}" == "255" ]; then
-  echo -en "\033[0;31m"
-  echo "Permission denied (publickey)."
-  echo -en "\033[0m"
+  echo -e "${red}ERROR: Permission denied (publickey).${reset}" >&2
   exit 1
 fi
 
@@ -107,17 +105,13 @@ fi
 if [ -n "${user}" ]; then
   resource="users/${user}/repos"
   if ! curl --fail --silent "https://api.github.com/users/${user}" >/dev/null ; then
-    echo -en "\033[0;31m"
-    echo "ERROR: GitHub user does not exist." >&2
-    echo -en "\033[0m\n"
+    echo -e "${red}ERROR: GitHub user does not exist.${reset}" >&2
     exit 1
   fi
 elif [ -n "${org}" ]; then
   resource="orgs/${org}/repos"
   if ! curl --fail --silent "https://api.github.com/orgs/${org}" >/dev/null; then
-    echo -en "\033[0;31m"
-    echo "ERROR: GitHub organization does not exist." >&2
-    echo -en "\033[0m\n"
+    echo -e "${red}ERROR: GitHub organization does not exist.${reset}" >&2
     exit 1
   fi
 else
@@ -147,17 +141,11 @@ for ssh_url in "${ssh_urls[@]}"; do
   output=$(git clone "${ssh_url}" 2>&1)
 
   if [[ "${output}" =~ 'already exists' ]]; then
-    echo -en "\033[0;31m"
-    echo "Repository already exists."
-    echo -en "\033[0m"
+    echo -e "${red}Repository already exists.${reset}"
   elif [[ "${output}" =~ 'not found' ]]; then
-    echo -en "\033[0;31m"
-    echo "Please make sure you have the correct access rights and the repository exists."
-    echo -en "\033[0m"
+    echo -e "${red}Please make sure you have the correct access rights and the repository exists.${reset}"
   elif [[ "${output}" =~ 'SAML' ]]; then
-    echo -en "\033[0;31m"
-    echo "ERROR: The '${org}' organization has enabled or enforced SAML SSO" >&2
-    echo -en "\033[0m"
+    echo -e "${red}ERROR: The '${org}' organization has enabled or enforced SAML SSO${reset}" >&2
   fi
 
 done
diff --git a/git-remote-v b/git-remote-v
--- a/git-remote-v
+++ b/git-remote-v
@@ -15,6 +15,11 @@
 # EXAMPLES
 #   None
 
+# Colors
+red='\033[0;31m'
+green='\033[0;32m'
+reset='\033[0m'
+
 # Print usage information.
 function usage() {
   echo "usage: $0 [OPTIONS] [DIR]"
@@ -42,9 +47,7 @@ if [ -z "${dir}" ]; then
   dir="$(pwd)"
 else
   if [ ! -e "${dir}" ]; then
-    echo -en "\033[0;31m"
-    echo "${dir} does not exist."
-    echo -en "\033[0m\n"
+    echo -e "${red}ERROR: ${dir} does not exist.${reset}" >&2
     exit 1
   fi
 fi
@@ -56,17 +59,15 @@ for d in "${dir}"/*; do
   basename "${d}"
 
   if [ ! -d "${d}/.git" ]; then
-    echo -en "\033[0;31m"
-    echo "$(basename "${d}") is not a Git repository."
-    echo -en "\033[0m"
+    echo -e "${red}$(basename "${d}") is not a Git repository.${reset}"
     continue
   fi
 
   pushd "${d}" >/dev/null || exit
 
-  echo -en "\033[0;32m" # display green
+  echo -e "${green}"
   git remote -v
-  echo -en "\033[0m"
+  echo -e "${reset}"
 
   popd >/dev/null || exit
 
diff --git a/git-status b/git-status
--- a/git-status
+++ b/git-status
@@ -15,6 +15,12 @@
 # EXAMPLES
 #   None
 
+# Colors
+red='\033[0;31m'
+green='\033[0;32m'
+yellow='\033[0;33m'
+reset='\033[0m'
+
 # Print usage information.
 function usage() {
   echo "usage: $0 [OPTIONS] [DIR]"
@@ -42,9 +48,7 @@ if [ -z "${dir}" ]; then
   dir="$(pwd)"
 else
   if [ ! -e "${dir}" ]; then
-    echo -en "\033[0;31m"
-    echo "${dir} does not exist."
-    echo -en "\033[0m\n"
+    echo -e "${red}ERROR: ${dir} does not exist.${reset}" >&2
     exit 1
   fi
 fi
@@ -56,9 +60,7 @@ for d in "${dir}"/*; do
   basename "${d}"
 
   if [ ! -d "${d}/.git" ]; then
-    echo -en "\033[0;31m"
-    echo "$(basename "${d}") is not a Git repository."
-    echo -en "\033[0m"
+    echo -e "${red}$(basename "${d}") is not a Git repository.${reset}"
     continue
   fi
 
@@ -67,21 +69,13 @@ for d in "${dir}"/*; do
   output=$(git status 2>&1)
 
   if [[ "${output}" =~ modified ]]; then
-    echo -en "\033[0;31m" # display red
-    echo "Modified files"
-    echo -en "\033[0m"
+    echo -e "${red}Modified files${reset}"
   elif [[ "${output}" =~ untracked ]]; then
-    echo -en "\033[0;31m" # display red
-    echo "Untracked files"
-    echo -en "\033[0m"
+    echo -e "${red}Untracked files${reset}"
   elif [[ "${output}" =~ ahead ]]; then
-    echo -en "\033[0;33m" # display yellow
-    echo "Use \"git push\" to publish your local commits"
-    echo -en "\033[0m"
+    echo -e "${yellow}Use \"git push\" to publish your local commits${reset}"
   else
-    echo -en "\033[0;32m" # display green
-    echo "Working tree clean."
-    echo -en "\033[0m"
+    echo -e "${green}Working tree clean.${reset}"
   fi
 
   popd >/dev/null || exit
diff --git a/slugify b/slugify
--- a/slugify
+++ b/slugify
@@ -16,6 +16,10 @@
 # EXAMPLES
 #   None
 
+# Colors
+red='\033[0;31m'
+reset='\033[0m'
+
 # Print usage information.
 function usage() {
   echo "usage: $0 [OPTIONS]"
@@ -35,12 +39,12 @@ while [[ $# -gt 0 ]]; do
 done
 
 if ! [ -x "$(command -v pbcopy)"  ]; then
-  echo 'Error: pbcopy is not installed.' >&2
+  echo -e "${red}ERROR: pbcopy is not installed.${reset}" >&2
   exit 1
 fi
 
 if ! [ -x "$(command -v pbpaste)"  ]; then
-  echo 'Error: pbpaste is not installed.' >&2
+  echo -e "${red}ERROR: pbpaste is not installed.${reset}" >&2
   exit 1
 fi
 
