Fix SSH test

diff --git a/git-clone-gh b/git-clone-gh
--- a/git-clone-gh
+++ b/git-clone-gh
@@ -118,8 +118,10 @@ eval "$(ssh-agent -s)" >/dev/null 2>&1 &&
   ssh-add "${HOME}/.ssh/${identity_file}" >/dev/null 2>&1
 
 # Test SSH connection to GitHub.
-if ! ssh -T git@github.com >/dev/null 2>&1; then
-  echo -e "${red}ERROR: Permission denied (publickey).${reset}" >&2
+ssh_output=$(ssh -T git@github.com 2>&1)
+if [[ ! "$ssh_output" =~ "successfully authenticated" ]]; then
+  echo -e "${red}ERROR: GitHub SSH authentication failed.${reset}" >&2
+  echo "$ssh_output" >&2
   exit 1
 fi
 
