Make yabai-cycle-firefox more general by allowing any application to be passed as an argument

diff --git a/yabai-cycle b/yabai-cycle
--- a/yabai-cycle
+++ b/yabai-cycle
@@ -1,16 +1,15 @@
 #!/usr/bin/env bash
 #
 # DESCRIPTION
-#   Focus and show Firefox (bring floating window to front).
+#   Focus and show an application (bring floating window to front).
 #
-#   If multiple Firefox windows exist, cycle through windows on successive
-#   invocations.
+#   If multiple windows exist, cycle through windows on successive invocations.
 #
 # USAGE
-#   yabai-cycle-firefox [OPTIONS]
+#   yabai-cycle [OPTIONS] APP
 #
 # ARGUMENTS
-#   None
+#   APP    Application to focus and show
 #
 # OPTIONS
 #   -h, --help    Show this help message
@@ -18,9 +17,16 @@
 # EXAMPLES
 #   None
 
+# Colors
+red='\033[0;31m'
+reset='\033[0m'
+
 # Print usage information.
 function usage() {
-  echo "usage: yabai-cycle-firefox [OPTIONS]"
+  echo "usage: yabai-cycle [OPTIONS] APP"
+  echo ""
+  echo "Arguments:"
+  echo "  APP    Application to focus and show"
   echo ""
   echo "Options:"
   echo "  -h, --help    Show this help message"
@@ -40,35 +46,40 @@ while [[ $# -gt 0 ]]; do
       exit 1
       ;;
     *)
-      echo "Unknown argument: $1" >&2
-      usage
-      exit 1
+      app="$1"
+      shift
+      break
       ;;
   esac
 done
 
-# Get the ID of the Firefox window currently in focus. Otherwise, set to an
-# empty string.
+if [ -z "${app}" ]; then
+  echo -e "${red}ERROR: Must specify an application.${reset}" >&2
+  usage
+  exit 1
+fi
+
+# Get the ID of the window currently in focus. Otherwise, set to an empty
+# string.
 current=$(yabai -m query --windows --window 2>/dev/null |
-  jq -r 'select(.app == "Firefox") | .id // empty' 2>/dev/null)
+  jq -r "select(.app == \"${app}\") | .id // empty" 2>/dev/null)
 
-# Get the IDs of all Firefox windows.
+# Get the IDs of all windows.
 ids=$(yabai -m query --windows 2>/dev/null |
-  jq -r '.[] | select(.app == "Firefox") | .id' 2>/dev/null | sort -n)
+  jq -r ".[] | select(.app == \"${app}\") | .id" 2>/dev/null | sort -n)
 
-# If no Firefox windows exist, open the application.
+# If no windows exist, open the application.
 if [ -z "${ids}" ]; then
-  open -a "Firefox"
+  open -a "${app}"
   exit 0
 fi
 
 if [ -z "${current}" ]; then
-  # If the current window is not Firefox, set $next to the first window in
-  # $ids.
+  # If the current window is not $app, set $next to the first window in $ids.
   next=$(echo "${ids}" | head -n 1)
 else
-  # Else, the current window is Firefox, therefore set $next to the next window
-  # in $ids.
+  # Else, the current window is $app, therefore set $next to the next window in
+  # $ids.
   next=$(echo "${ids}" | grep -A 1 "^${current}$" | tail -n 1)
   # Cycle to the first window in $ids.
   if [ "$next" = "$current" ] || [ -z "$next" ]; then
